#!/usr/bin/perl -w

use strict;

opendir( DIR, "." );
my @files = readdir( DIR );
closedir( DIR );

open( FILE, "> merged.tcx" ) or die $!;

print FILE header();

foreach my $file ( @files ) {
  next unless $file =~ /^activity_\d+\.tcx$/;
  open( INPUT, $file ) or die $!;
  my $content = join( "", <INPUT> );
  ( my $activity ) = $content =~ /(\<Activity.+\<\/Activity\>)/s;
  print FILE $activity, "\n";
}

print FILE footer();

close( FILE );

sub header {
  return <<EOQ;
<?xml version="1.0" encoding="UTF-8"?>
<TrainingCenterDatabase
  xsi:schemaLocation="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2 http://www.garmin.com/xmlschemas/TrainingCenterDatabasev2.xsd"
      xmlns:ns5="http://www.garmin.com/xmlschemas/ActivityGoals/v1"
	  xmlns:ns3="http://www.garmin.com/xmlschemas/ActivityExtension/v2"
	      xmlns:ns2="http://www.garmin.com/xmlschemas/UserProfile/v2"
  xmlns="http://www.garmin.com/xmlschemas/TrainingCenterDatabase/v2"
    xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:ns4="http://www.garmin.com/xmlschemas/ProfileExtension/v1">
  <Activities>
EOQ
  ;
}

sub footer {
  return <<EOQ;
  </Activities>
  <Author xsi:type="Application_t">
    <Name>Garmin Connect API</Name>
    <Build>
      <Version>
        <VersionMajor>0</VersionMajor>
        <VersionMinor>0</VersionMinor>
        <BuildMajor>0</BuildMajor>
        <BuildMinor>0</BuildMinor>
      </Version>
    </Build>
    <LangID>en</LangID>
    <PartNumber>GAR-MINCN-CT</PartNumber>
  </Author>
</TrainingCenterDatabase>
EOQ
  ;
}
